### ISSUE TITLE
Math Transitions

### ISSUE THREAD

**Issue by bridgebrain** [pytti-tools/pytti-core#120]
Math Transition
So what if there was a setup that let your math convert from one motion system to another over time?

Like Math A (translate x, translate y, translate z rotate [wxyz])

Like Math B (translate x, translate y, translate z rotate [wxyz])

interpolation steps:

Granted this requires A: knowing the math, and B: doing lots of error clamping, or only allowing similar math systems (can't change a sin to a cosin halfway through)

Also, we should find a good resource for visualising the math, because I'm willing to brute force the numbers until they work, but it'd be good to see what it looks like without half an hour of exports

**Comment by dmarx** [comment]
I added numpy to the parameteric_eval math env. you can invoke numpy functions using the `np` alias. calling this closed?
