### ISSUE TITLE
Weighted values placed in an init as a module

### ISSUE THREAD

**Issue by bridgebrain** [pytti-tools/pytti-core#121]
So like, one occasional problem getting the exact results I'm looking is that the AI has a context-free understanding of space and geometry. In a lot of ways, this is the charm of Pytti and such, if it just looked like an accurate 3d render of a scene it'd lose a lot of its ineffable quality.

That said, something that could get me closer to my results and also be a big upgrade would be the option to create an init protocol (I like calling it 'positioning_init' when thinking of it) that would read the words off a white init with prompt words on it. It could be simple/complex, either just establishing a general zone, or demarking the layout of everything. Later additions could be scaling the text to different sizes to cause depth effects, and text colors other than black to establish color perferences in those areas. The AI already does encoding for images, so this would cut out the middleman in that code, with only "prompt at position". It would, I imagine, act like weighting in "areas" such as middle distance between one prompt and the next. So the top half gets blue sky:1, the bottom half gets grassy lawn: 1.

Having typed all that out, I realize masking might already be being used for this, haven't messed with it yet

Edit: Examples https://imgur.com/a/qS8gcgB

**Comment by dmarx** [comment]
yeah I think this is basically the same as assigning a mask to a prompt, closing
