### ISSUE TITLE
Depth map

### ISSUE THREAD

**Issue by bridgebrain** [pytti-tools/pytti-core#122]
Previously, we discussed the possibility of getting depth maps outputted per frame.

On top of this, does the depth map that pytti uses do the black-white, or the purple-orange? If it does the latter(or can be easily switched to it), while adding the option of outputting depthmap frames, it could be included as a low weighted color image, and then your image will most likely have [chroma-depth](http://www.jaredjared.com/chroma/artsy.jpg). For that matter, someone may just have a chroma-depth depth map model around

Also if we can get detailed depth-map frames, we can use the result to create detailed trippy 3d printable objects, with some tweaking. As a note for that, maybe a setting to force the compute to spend extra time on the depth map?

**Comment by dmarx** [comment]
moved to #132
