### ISSUE TITLE
running pytti = no images output

### ISSUE THREAD

**Issue by lltowe** [pytti-tools/pytti-core#172]
Hi David

I am running pytti.workhorse from the command line
i.e.  python -m pytti.workhorse

(note I have animation setttings off, just looking for the inital image to start off)

I see some debug and info output, including the warnings below

-----
```
/home/loyd/anaconda3/envs/pytti-tools/lib/python3.10/site-packages/pytti/workhorse.py:186: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="config", config_name="default")
```

```
/home/loyd/anaconda3/envs/pytti-tools/lib/python3.10/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/next/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
```
```

/home/loyd/anaconda3/envs/pytti-tools/lib/python3.10/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755897462/work/aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
```
-----

Then it displays the settings string.  Appears to run through all the image iterations.  Then terminates.   The correct folder in images_out is created and the settings.txt file is created.  However no images at all.

BELOW IS THE SETTINGS FILE
-----
```
{"scenes": "deep space habitation ring made of glass | galactic nebula | wow! space is full of fractal creatures darting around everywhere like fireflies", "scene_prefix": "astrophotography #pixelart | image credit nasa | space full of cybernetic neon:3_galactic nebula | isometric pixelart by Sachin Teng | ", "scene_suffix": "| satellite image:-1:-.95 | text:-1:-.95 | anime:-1:-.95 | watermark:-1:-.95 | backyard telescope:-1:-.95 | map:-1:-.95", "direct_image_prompts": "", "init_image": "", "direct_init_weight": "", "semantic_init_weight": "", "image_model": "Limited Palette", "vqgan_model": "openimages", "animation_mode": "off", "width": 512, "height": 512, "steps_per_scene": 200, "steps_per_frame": 50, "interpolation_steps": 0, "learning_rate": 0.1, "reset_lr_each_frame": true, "seed": "919809", "cutouts": 40, "cut_pow": 2, "cutout_border": 0.25, "border_mode": "wrap", "field_of_view": 60, "near_plane": 1, "far_plane": 10000, "input_audio": "", "input_audio_offset": 0, "input_audio_filters": [], "pre_animation_steps": 100, "lock_camera": true, "translate_x": "0", "translate_y": "0", "translate_z_3d": "0", "rotate_3d": "[1, 0, 0, 0]", "rotate_2d": "0", "zoom_x_2d": "0", "zoom_y_2d": "0", "sampling_mode": "bicubic", "infill_mode": "wrap", "pixel_size": 1, "smoothing_weight": 0.1, "random_initial_palette": true, "palette_size": 6, "palettes": 9, "gamma": 1, "hdr_weight": 0.01, "palette_normalization_weight": 0.2, "show_palette": false, "target_palette": "", "lock_palette": false, "frames_per_second": 12, "direct_stabilization_weight": "", "semantic_stabilization_weight": "", "depth_stabilization_weight": "", "edge_stabilization_weight": "", "flow_stabilization_weight": "", "video_path": "", "frame_stride": 1, "reencode_each_frame": true, "flow_long_term_samples": 1, "ViTB32": true, "ViTB16": true, "ViTL14": false, "ViTL14_336px": false, "RN50": false, "RN101": false, "RN50x4": false, "RN50x16": false, "RN50x64": false, "file_namespace": "next", "allow_overwrite": true, "display_every": 25, "clear_every": 0, "display_scale": 1, "save_every": 50, "backups": 0, "show_graphs": false, "approximate_vram_usage": false, "use_tensorboard": true, "models_parent_dir": "/home/loyd/.cache", "gradient_accumulation_steps": 1, "conf": {}}

b'0.00: astrophotography #pixelart | image credit nasa | space full of cybernetic neon:3_galactic nebula | isometric pixelart by Sachin Teng | deep space habitation ring made of glass | galactic nebula | wow! space is full of fractal creatures darting around everywhere like fireflies| satellite image:-1:-.95 | text:-1:-.95 | anime:-1:-.95 | watermark:-1:-.95 | backyard telescope:-1:-.95 | map:-1:-.95'
```
----- END OF SETTINGS FILE

ubuntu 22.04

python version = 3.10.4

GPU=RTX3060 / 12 gb

BELOW IS THE PIP FREEZE OUTPUT
----
absl-py==1.0.0
adjustText==0.7.3
aiohttp==3.8.1
aiosignal==1.2.0
antlr4-python3-runtime==4.9.3
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
async-timeout==4.0.2
attrs==21.4.0
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.0
brotlipy==0.7.0
cachetools==5.1.0
certifi==2022.5.18.1
cffi @ file:///home/builder/ci_310/cffi_1642753365720/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
clip @ file:///home/loyd/pytti-notebook/pytti-core/vendor/CLIP
cryptography @ file:///tmp/build/80754af9/cryptography_1652101588599/work
cycler==0.11.0
debugpy==1.6.0
decorator==5.1.1
defusedxml==0.7.1
einops==0.4.1
entrypoints==0.4
executing==0.8.3
exrex==0.10.5
fastjsonschema==2.15.3
filelock==3.7.0
fonttools==4.33.3
frozenlist==1.3.0
fsspec==2022.5.0
ftfy==6.1.1
gdown==4.4.0
google-auth==2.6.6
google-auth-oauthlib==0.4.6
grpcio==1.46.3
hydra-core==1.2.0
idna @ file:///tmp/build/80754af9/idna_1637925883363/work
imageio @ file:///home/conda/feedstock_root/build_artifacts/imageio_1652789504106/work
ipykernel==6.13.0
ipython==8.3.0
ipython-genutils==0.2.0
ipywidgets==7.7.0
jedi==0.18.1
Jinja2==3.1.2
jsonschema==4.5.1
jupyter==1.0.0
jupyter-client==7.3.1
jupyter-console==6.4.3
jupyter-core==4.10.0
jupyterlab-pygments==0.2.2
jupyterlab-widgets==1.1.0
kiwisolver==1.4.2
kornia==0.6.5
loguru==0.6.0
Markdown==3.3.7
MarkupSafe==2.1.1
matplotlib==3.5.2
matplotlib-inline==0.1.3
matplotlib-label-lines==0.5.1
mistune==0.8.4
mkl-fft==1.3.1
mkl-random @ file:///home/builder/ci_310/mkl_random_1641843545607/work
mkl-service==2.4.0
more-itertools==8.13.0
multidict==6.0.2
nbclient==0.6.3
nbconvert==6.5.0
nbformat==5.4.0
nest-asyncio==1.5.5
notebook==6.4.11
numpy @ file:///opt/conda/conda-bld/numpy_and_numpy_base_1652801679809/work
oauthlib==3.2.0
omegaconf==2.2.1
opencv-python==4.5.5
packaging==21.3
pandas==1.4.2
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1652814985504/work
prometheus-client==0.14.1
prompt-toolkit==3.0.29
protobuf==3.20.1
psutil==5.9.1
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pyDeprecate==0.3.2
PyGLM==2.5.7
Pygments==2.12.0
pyOpenSSL @ file:///opt/conda/conda-bld/pyopenssl_1643788558760/work
pyparsing==3.0.9
pyrsistent==0.18.1
PySocks @ file:///home/builder/ci_310/pysocks_1640793678128/work
python-dateutil==2.8.2
pytorch-lightning==1.6.3
pyttitools-adabins @ file:///home/loyd/pytti-notebook/pytti-core/vendor/AdaBins
pyttitools-core @ file:///home/loyd/pytti-notebook/pytti-core
pyttitools-gma @ file:///home/loyd/pytti-notebook/pytti-core/vendor/GMA
pyttitools-taming-transformers @ file:///home/loyd/pytti-notebook/pytti-core/vendor/taming-transformers
pytz==2022.1
PyYAML==6.0
pyzmq==23.0.0
qtconsole==5.3.0
QtPy==2.1.0
regex==2022.4.24
requests @ file:///opt/conda/conda-bld/requests_1641824580448/work
requests-oauthlib==1.3.1
rsa==4.8
scipy==1.8.1
seaborn==0.11.2
Send2Trash==1.8.0
six @ file:///tmp/build/80754af9/six_1644875935023/work
soupsieve==2.3.2.post1
stack-data==0.2.0
tensorboard==2.9.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
terminado==0.15.0
tinycss2==1.1.1
torch==1.11.0
torchaudio==0.11.0
torchmetrics==0.8.2
torchvision==0.12.0
tornado==6.1
tqdm==4.64.0
traitlets==5.2.1.post0
typing_extensions @ file:///opt/conda/conda-bld/typing_extensions_1647553014482/work
urllib3 @ file:///opt/conda/conda-bld/urllib3_1650637206367/work
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==2.1.2
widgetsnbextension==3.6.0
yarl==1.7.2
----- END OF PIP FREEZE

BELOW IS THE CONDA LIST OUTPUT
-----
# packages in environment at /home/loyd/anaconda3/envs/pytti-tools:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   1.0.0                    pypi_0    pypi
adjusttext                0.7.3                    pypi_0    pypi
aiohttp                   3.8.1                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
alsa-lib                  1.2.6.1              h7f98852_0    conda-forge
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
aom                       3.3.0                h27087fc_1    conda-forge
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
asttokens                 2.0.5                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
blas                      1.0                         mkl  
bleach                    5.0.0                    pypi_0    pypi
brotlipy                  0.7.0           py310h7f8727e_1002  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.5.18.1          ha878542_0    conda-forge
cachetools                5.1.0                    pypi_0    pypi
cairo                     1.16.0            ha12eb4b_1010    conda-forge
certifi                   2022.5.18.1     py310hff52083_0    conda-forge
cffi                      1.15.0          py310hd667e15_1  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
clip                      1.0                      pypi_0    pypi
cryptography              37.0.1          py310h9ce1e76_0  
cudatoolkit               11.3.1               h2bc3f7f_2  
cycler                    0.11.0                   pypi_0    pypi
dbus                      1.13.6               h5008d03_3    conda-forge
debugpy                   1.6.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
einops                    0.4.1                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 0.8.3                    pypi_0    pypi
expat                     2.4.8                h27087fc_0    conda-forge
exrex                     0.10.5                   pypi_0    pypi
fastjsonschema            2.15.3                   pypi_0    pypi
ffmpeg                    4.4.1                hd7ab26d_2    conda-forge
filelock                  3.7.0                    pypi_0    pypi
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.33.3                   pypi_0    pypi
freeglut                  3.2.2                h9c3ff4c_1    conda-forge
freetype                  2.11.0               h70c0345_0  
frozenlist                1.3.0                    pypi_0    pypi
fsspec                    2022.5.0                 pypi_0    pypi
ftfy                      6.1.1                    pypi_0    pypi
gdown                     4.4.0                    pypi_0    pypi
gettext                   0.19.8.1          h73d1719_1008    conda-forge
giflib                    5.2.1                h7b6447c_0  
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.15               he1e5248_0  
google-auth               2.6.6                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
graphite2                 1.3.13            h58526e2_1001    conda-forge
grpcio                    1.46.3                   pypi_0    pypi
gst-plugins-base          1.20.2               hf6a322e_1    conda-forge
gstreamer                 1.20.2               hd4edc92_1    conda-forge
harfbuzz                  4.2.0                h40b6f09_0    conda-forge
hdf5                      1.12.1          nompi_h4df4325_104    conda-forge
hydra-core                1.2.0                    pypi_0    pypi
icu                       69.1                 h9c3ff4c_0    conda-forge
idna                      3.3                pyhd3eb1b0_0  
imageio                   2.19.2             pyhcf75d05_0    conda-forge
intel-openmp              2021.4.0          h06a4308_3561  
ipykernel                 6.13.0                   pypi_0    pypi
ipython                   8.3.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.7.0                    pypi_0    pypi
jasper                    2.0.33               ha77e612_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jpeg                      9e                   h7f8727e_0  
jsonschema                4.5.1                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            7.3.1                    pypi_0    pypi
jupyter-console           6.4.3                    pypi_0    pypi
jupyter-core              4.10.0                   pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        1.1.0                    pypi_0    pypi
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.2                    pypi_0    pypi
kornia                    0.6.5                    pypi_0    pypi
krb5                      1.19.3               h08a2579_0    conda-forge
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0            12_linux64_mkl    conda-forge
libcblas                  3.9.0            12_linux64_mkl    conda-forge
libclang                  13.0.1          default_hc23dcda_0    conda-forge
libcurl                   7.83.1               h2283fc2_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libdrm                    2.4.109              h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h28343ad_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0               h1234567_0  
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libglib                   2.70.2               h174f98d_4    conda-forge
libglu                    9.0.0             he1b5a44_1001    conda-forge
libgomp                   11.2.0               h1234567_0  
libiconv                  1.16                 h7f8727e_2  
libidn2                   2.3.2                h7f8727e_0  
liblapack                 3.9.0            12_linux64_mkl    conda-forge
liblapacke                3.9.0            12_linux64_mkl    conda-forge
libllvm13                 13.0.1               hf817b99_2    conda-forge
libnghttp2                1.47.0               he49606f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopencv                 4.5.5           py310h1897127_9    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpciaccess              0.16                 h516909a_0    conda-forge
libpng                    1.6.37               hbc83047_0  
libpq                     14.3                 he2d8382_0    conda-forge
libprotobuf               3.20.1               h6239696_0    conda-forge
libssh2                   1.10.0               ha35d2d1_2    conda-forge
libstdcxx-ng              11.2.0               h1234567_0  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.3.0                h542a066_3    conda-forge
libunistring              0.9.10               h27cfd23_0  
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.40.0               h7b6447c_0  
libva                     2.14.0               h7f98852_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libvpx                    1.11.0               h9c3ff4c_3    conda-forge
libwebp                   1.2.2                h55f646e_0  
libwebp-base              1.2.2                h7f8727e_0  
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
loguru                    0.6.0                    pypi_0    pypi
lz4-c                     1.9.3                h295c915_1  
markdown                  3.3.7                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.2                    pypi_0    pypi
matplotlib-inline         0.1.3                    pypi_0    pypi
matplotlib-label-lines    0.5.1                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0           py310h7f8727e_0  
mkl_fft                   1.3.1           py310hd6ae3a3_0  
mkl_random                1.2.2           py310h00e6091_0  
more-itertools            8.13.0                   pypi_0    pypi
multidict                 6.0.2                    pypi_0    pypi
mysql-common              8.0.29               h26416b9_1    conda-forge
mysql-libs                8.0.29               hbc51c84_1    conda-forge
nbclient                  0.6.3                    pypi_0    pypi
nbconvert                 6.5.0                    pypi_0    pypi
nbformat                  5.4.0                    pypi_0    pypi
ncurses                   6.3                  h7f8727e_2  
nest-asyncio              1.5.5                    pypi_0    pypi
nettle                    3.7.3                hbbd107a_1  
notebook                  6.4.11                   pypi_0    pypi
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.77                 h2350873_0    conda-forge
numpy                     1.22.3          py310hfa59a62_0  
numpy-base                1.22.3          py310h9585f30_0  
oauthlib                  3.2.0                    pypi_0    pypi
omegaconf                 2.2.1                    pypi_0    pypi
opencv                    4.5.5           py310hff52083_9    conda-forge
openh264                  2.1.1                h4ff587b_0  
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   3.0.3                h166bdaf_0    conda-forge
packaging                 21.3                     pypi_0    pypi
pandas                    1.4.2                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pcre                      8.45                 h9c3ff4c_0    conda-forge
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.1.1           py310he619898_0    conda-forge
pip                       21.2.4          py310h06a4308_0  
pixman                    0.40.0               h36c2ea0_0    conda-forge
prometheus-client         0.14.1                   pypi_0    pypi
prompt-toolkit            3.0.29                   pypi_0    pypi
protobuf                  3.20.1                   pypi_0    pypi
psutil                    5.9.1                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
py-opencv                 4.5.5           py310hfdc917e_9    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pydeprecate               0.3.2                    pypi_0    pypi
pyglm                     2.5.7                    pypi_0    pypi
pygments                  2.12.0                   pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
pysocks                   1.7.1           py310h06a4308_0  
python                    3.10.4          h2660328_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.10                    2_cp310    conda-forge
pytorch                   1.11.0          py3.10_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-lightning         1.6.3                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pyttitools-adabins        0.0.1                    pypi_0    pypi
pyttitools-core           0.0.1                    pypi_0    pypi
pyttitools-gma            0.0.1                    pypi_0    pypi
pyttitools-taming-transformers 0.0.1                    pypi_0    pypi
pytz                      2022.1                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     23.0.0                   pypi_0    pypi
qt                        5.12.9               h1304e3e_6    conda-forge
qtconsole                 5.3.0                    pypi_0    pypi
qtpy                      2.1.0                    pypi_0    pypi
readline                  8.1.2                h7f8727e_1  
regex                     2022.4.24                pypi_0    pypi
requests                  2.27.1             pyhd3eb1b0_0  
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
scipy                     1.8.1                    pypi_0    pypi
seaborn                   0.11.2                   pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                61.2.0          py310h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlite                    3.38.5               h4ff8645_0    conda-forge
stack-data                0.2.0                    pypi_0    pypi
svt-av1                   0.9.1                h27087fc_0    conda-forge
tensorboard               2.9.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
terminado                 0.15.0                   pypi_0    pypi
tinycss2                  1.1.1                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
torchaudio                0.11.0              py310_cu113    pytorch
torchmetrics              0.8.2                    pypi_0    pypi
torchvision               0.12.0              py310_cu113    pytorch
tornado                   6.1                      pypi_0    pypi
tqdm                      4.64.0                   pypi_0    pypi
traitlets                 5.2.1.post0              pypi_0    pypi
typing_extensions         4.1.1              pyh06a4308_0  
tzdata                    2022a                hda174b7_0  
urllib3                   1.26.9          py310h06a4308_0  
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
werkzeug                  2.1.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        3.6.0                    pypi_0    pypi
x264                      1!161.3030           h7f98852_1    conda-forge
x265                      3.5                  h924138e_3    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h7f8727e_1  
yarl                      1.7.2                    pypi_0    pypi
zlib                      1.2.11            h166bdaf_1014    conda-forge
zstd                      1.5.2                h8a70e8d_1    conda-forge
----- END OF CONDA LIST

**Comment by lltowe** [comment]
Well how about that.  Was there all the time.  Glad to know it is working and I can stop trying to fix it now!  Thanks David

/home/loyd/pytti-notebook/outputs/2022-05-26/07-12-48/images_out/next/next_4.png

**Comment by dmarx** [comment]
my pleasure! I'll try to document this weird behavior better
