### ISSUE TITLE
problem with 3D animation after update

### ISSUE THREAD

**Issue by CuchulainnPrimus** [pytti-tools/pytti-core#198]
Since the update last night I have a problem generating 3D animation. Already tried removing everything on the google drive, and rerunning it, but that didn't work. Here is the error message I get:

[/usr/local/lib/python3.7/dist-packages/pytti/LossAug/OpticalFlowLossClass.py](https://localhost:8080/#) in set_last_step(self, last_step_pil, device)
    168         """
    169         if device is None:
--> 170             device = getattr(self, "device", last_step_pil.device)
    171         last_step = (
    172             TF.to_tensor(last_step_pil)

AttributeError: 'Image' object has no attribute 'device'

**Comment by dmarx** [comment]
thanks for reporting this bug! I just pushed a change that should fix this, let me know if it works. if it doesn't, try factory resetting the colab instance to re-install with the latest version of the codebase.

**Comment by dmarx** [comment]
also, could you share your settings? this wasn't caught in my tests and I'd like to see if I can use your settings to identify the gap in test coverage.

**Comment by CuchulainnPrimus** [comment]
That was quick! It is working again now, thanks!
