### ISSUE TITLE
Fails due to issue with logs folder when running the demo configuration

### ISSUE THREAD

**Issue by ricardomatias** [pytti-tools/pytti-core#45]
Fails with:

> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/home/ares/miniconda3/envs/pytti-tools/lib/python3.9/threading.py", line 950, in _bootstrap_inner
>     self.run()
>   File "/home/ares/miniconda3/envs/pytti-tools/lib/python3.9/site-packages/tensorboard/summary/writer/event_file_writer.py", line 233, in run
>     self._record_writer.write(data)
>   File "/home/ares/miniconda3/envs/pytti-tools/lib/python3.9/site-packages/tensorboard/summary/writer/record_writer.py", line 40, in write
>     self._writer.write(header + header_crc + data + footer_crc)
>   File "/home/ares/miniconda3/envs/pytti-tools/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 766, in write
>     self.fs.append(self.filename, file_content, self.binary_mode)
>   File "/home/ares/miniconda3/envs/pytti-tools/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 160, in append
>     self._write(filename, file_content, "ab" if binary_mode else "a")
>   File "/home/ares/miniconda3/envs/pytti-tools/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 164, in _write
>     with io.open(filename, mode, encoding=encoding) as f:
> FileNotFoundError: [Errno 2] No such file or directory: b'logs/events.out.tfevents.1644749727.pop-os.38487.0'
>  10%|███████████▌

**Comment by dmarx** [comment]
Try creating a logs folder

**Comment by ricardomatias** [comment]
There is one with similarly named files

**Comment by dmarx** [comment]
try deleting the logs folder and starting again. Maybe I'll add something to allow people who aren't using tensorboard to turn off the sumarywriter

**Comment by ricardomatias** [comment]
It didn't help. Perhaps the docs should mention tensorboard, how to make use of it.

**Comment by dmarx** [comment]
very weird... I wish I could replicate this. Could you tell me a little more about your environment? What OS are you using? Are you able to get other ML code to run locally?

**Comment by dmarx** [comment]
unable to replicate, no other users have reported similar issue. closing for now, but please reopen if issue persists even after updating to most current version of pytti.
