### ISSUE TITLE
cleanup pytti.Image.VQGANImage.init_image

### ISSUE THREAD

**Issue by dmarx** [pytti-tools/pytti-core#58]
this code is just a mess

**Comment by zzbuzzard** [comment]
Hey why was this closed? It doesn't seem to be fixed yet, though I can understand that it could be fixed as part of the general cleanup going on right now. I made a quick [branch](https://github.com/zzbuzzard/pytti-core/tree/VQGAN-download-no-subprocess) trying to address this, if it's still of use!

**Comment by dmarx** [comment]
oh lol, whoops! Yeah I was in a general cleanup mode when I closed this issue and honestly, I couldn't figure out precisely what the title was referring to. I clearly didn't look hard enough because judging from the comments in that file I think you found what I was complaining to myself about when I authored this issue.

**Comment by dmarx** [comment]
Created a PR from your branch, will take a closer look at your work tomorrow. Thanks for helping out!

**Comment by zzbuzzard** [comment]
Great thanks! Let me know if I can improve it.
